---
layout: page
title: "공간통계를 위한 데이터 사이언스"
subtitle: "강수량"
author: "[한국 R 사용자회](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography_spatial.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: bluee
editor_options: 
  chunk_output_type: console
---
 
``` {r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```


# 강수량 {#convert-example}

공공데이터포털에서 "기상청 지상(종관, ASOS) 일자료 조회서비스" API를 사용하여 
기상데이터를 가져와서 강수량 데이터를 가공한다.

```{r}
library(httr)
library(tidyverse)

rain_req <- glue::glue("http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList",
                       "?serviceKey={Sys.getenv('DATA_KMA_APIKEY')}",
                       "&numOfRows=10",
                       "&pageNo=1",
                       "&dataCd=ASOS",
                       "&dateCd=DAY",
                       "&startDt=20100101",
                       "&endDt=20220810",
                       "&stnIds=108",
                       "&dataType=JSON")

rain_response <- GET(rain_req, verbose())

rain_json <- content(rain_response, "text") 

rain_list <- jsonlite::fromJSON(rain_json)

rain_df <- rain_list$response$body$items$item

rain_df %>% 
  as_tibble() %>% 
  select(1:5)


```


