---
layout: page
title: "공간통계를 위한 데이터 사이언스"
subtitle: "The Spirit of Texas Bank"
author:
    name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
mainfont: NanumGothic
---


``` {r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```


# 데이터셋 {#dataset}

```{r dataset}
library(tidyverse)
library(tigris)
library(leaflet)
library(sf)

bank_df <- read_rds("data/bank.rds")

```

# 시각화 {#visualization}

## 인터랙티브 {#interactive-visualization}

```{r bank-leaflet}
library(glue)

bank_df %>% 
  leaflet() %>% 
    addProviderTiles(provider = providers$OpenStreetMap) %>% 
    addMarkers(lng=~location_lon, lat = ~location_lat, clusterOptions = markerClusterOptions(),
               popup = ~ as.character(glue("<strong> {offname} </strong> <br>
                                           &middot; Run Date: {rundate}")))
```

## Shapefile {#visualization-shapefile}

```{r bank-shapefile}
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
# tigris_cache_dir("/Users/statkclee/swc/tmp")

tx_counties <- counties(class = 'sf', state = 'TX', cb = TRUE, year = 2018)

leaflet(tx_counties) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(fillColor = "white",
              color = "black",
              weight = 0.5)
```

## static ggplot {#visualization-ggplot}

```{r bank-shapefile-static}
bank_sf <- bank_df %>%
  st_as_sf(coords = c("location_lon", "location_lat"), crs = 4269)

bank_branches <- bank_df %>% count(county) %>%  pull(county)

tx_counties <- tx_counties %>% 
  mutate(branch_tf = NAME %in% bank_branches)

ggplot() +
  geom_sf(data = tx_counties, aes(fill = branch_tf)) +
  geom_point(data=bank_df, aes(x=location_lon, y=location_lat), 
             size = 2) +
  theme_bw() +
  labs(fill = "Spirit of Texas Branches")
```


## 지점과 shapefile {#shapefile+point}

```{r shapefile-point}
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = tx_counties,
              fillColor = "white",
              color = "black",
              weight = 0.5) %>% 
    addMarkers(data = bank_df, lng=~location_lon, lat = ~location_lat, 
               popup = ~ as.character(glue("<strong> {offname} </strong> <br>
                                           &middot; Run Date: {rundate}")))
```

